### ISSUE TITLE
Shift Clicking does not work with Backpack Items

### ISSUE THREAD

**Issue by Space-Rose** [BeansGalaxy/Beans-Backpacks-2#16]
shift clicking on furnaces and any other like that only opens the menu and dose not let you place blocks down on them. I am playing in 1.20.1

**Comment by BeansGalaxy** [comment]
This has been an issue in all versions for a while but I can't narrow it down. Using the hotkey with an equipped backpack works fine but I don't know why the Item refuses to work. I'll make sure this is fixed in the full release but this isn't critical just annoying.

TLDR: You'll have to equip the backpack first then place it using the hotkey.
> At somepoint I do override the chain of code that runs when you right click with anything so you don't have to use sneak to place the backpack with the hotkey but I can't see how that could be the problem.

**Comment by Space-Rose** [comment]
oh I was meaning with or without the backpack on it still won't work, like trying to place a block on a crafting table it will just open the table and not place the block. unless you said that and my brain just isn't understanding.

**Comment by BeansGalaxy** [comment]
I meant if you are holding the Item in your hand and shift right click, the furnace or crafting table still opens. To my knowledge if you have it equipped hold CTRL and right click, it should place it regardless of what you're looking at.

I've known the Item has the issue of not shift right clicking but can't narrow down the issue yet.

**Comment by Space-Rose** [comment]
ok just making sure I understand, thank you for clarifying my confusion.

**Comment by BeansGalaxy** [comment]
Fixed in v2-0.8 for 1.20.2. Currently working on the port for 1.20.1
